name: Deploy Next.js to GitHub Pages

on:
  push:
    branches: [ "main" ]
  # You can also manually trigger this workflow:
  workflow_dispatch:

jobs:
  build-and-upload:
    name: Build and Upload to Artifact
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Install dependencies
        run: npm ci

      - name: Build project
        run: npm run build

      - name: Export static files
        run: npm run export

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v1
        with:
          path: ./out

  deploy:
    name: Deploy to GitHub Pages
    needs: build-and-upload
    runs-on: ubuntu-latest
    steps:
      - name: Deploy
        uses: actions/deploy-pages@v1
